---
- name: This is to test web URL
  hosts: web
  vars:
    url: http://192.168.18.3:8080/test_tomcat/
  tasks:
  - name: access the web url and capture the output.
    uri:
       url: "{{ url }}"
       method: GET
       return_content: yes
    register: web_output
  - name: Display the output.
    debug:
     var: web_output
  - name: Check status and display success or Failed
    debug:
     msg: "The URL is up and running fine"
    when: web_output.status == 200
