- name: Playbook for packages.yml
  hosts: all
  vars: 
    pkgs:
      - httpd
      - mariadb
  tasks:
  - name: install the packages
    yum:
     name: "{{ item }}"
     state: present
    loop: "{{ pkgs }}"
    when: inventory_hostname in groups['dev'] or inventory_hostname in groups['test'] or inventory_hostname in groups['prod']
  - name: install the RPM development tool package group
    yum:
      name: "@RPM Development tools"
      state: present
    when: inventory_hostname in groups['db']
  - name: update all packages
    yum:
       name: '*'
	     state: latest
    when: inventory_hostname in groups['webserver']