- hosts: node
  vars:
   webpackage: httpd
  tasks:
  - name: Install Apache Webserver in node01 server
    yum:
      name: "{{ webpackage }}"
      state: present
    register: install_output
  - name: start the service
    service:
            name: httpd
            state: started
            enabled: yes
  - debug:
      var: install.output